### ISSUE TITLE
Inititalising contructor variable

### ISSUE THREAD

**Issue by interludic** [diegobanos/php-glicko2#1]
Hey Mate,

Thanks for producing this, it has come in excellent timing for our project!

i get errors using your demo:
Too few arguments to function Diegobanos\Glicko2\Glicko2::__construct(), 0 passed in 

So i changed this line:
    public function __construct(float $tau, float $tol)

    public function __construct(float $tau=1, float $tol=1)

Am i missing something? wrong php version (7.2)?

**Comment by diegobanos** [comment]
Hey @interludic , thanks for the feedback.

You are right, the example I added on the README file was misleading since it was necessary to give both arguments. I followed your suggestion and I added default values for $tau and $tol in the Glicko2 class. The values I used are tau 0.5 and tol 0.000001.

You should keep the tolerance as 0.000001. Based on the glicko2 system, the tau value should be between 0.3 and 1.2. The more unpredictable the outcome of your game is, the smaller tau should be, to avoid big changes on rating.

I am closing this issue since it has been fixed on the last version. Thank you!
